spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://webappbddprodthomas.mysql.database.azure.com:3306/defaultdb?createDatabaseIfNotExist=true&autoReconnect=true&showSSL=false
    username: thomas
    password: Ilabrait10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true